//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BelibaHoma.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alert
    {
        public int Id { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int Status { get; set; }
        public string Notes { get; set; }
        public int AlertType { get; set; }
        public Nullable<int> LinkedTutorId { get; set; }
        public Nullable<int> LinkedTraineeId { get; set; }
        public Nullable<int> LinkedReportId { get; set; }
    
        public virtual Trainee Trainee { get; set; }
        public virtual Tutor Tutor { get; set; }
        public virtual TutorReport TutorReport { get; set; }
    }
}
