//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BelibaHoma.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int TraineeId { get; set; }
        public int SemesterNumber { get; set; }
        public int Grade1 { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int SemesterType { get; set; }
    
        public virtual Trainee Trainee { get; set; }
    }
}
