//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BelibaHoma.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOffer
    {
        public int Id { get; set; }
        public string JobTitle { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public System.DateTime CreationTime { get; set; }
        public int JobArea { get; set; }
        public string Requirements { get; set; }
        public string Description { get; set; }
        public int RelevantMajorId1 { get; set; }
        public Nullable<int> RelevantMajorId2 { get; set; }
        public Nullable<int> RelevantMajorId3 { get; set; }
        public string Organization { get; set; }
        public int JobType { get; set; }
        public string Address { get; set; }
        public Nullable<int> NumEmployees { get; set; }
        public string ContactName { get; set; }
        public string ContactMail { get; set; }
        public string ContactPhone { get; set; }
        public string ContactJobPosition { get; set; }
        public int JobStatus { get; set; }
    
        public virtual AcademicMajor AcademicMajor { get; set; }
        public virtual AcademicMajor AcademicMajor1 { get; set; }
        public virtual AcademicMajor AcademicMajor2 { get; set; }
    }
}
