//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BelibaHoma.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PredictionTraining
    {
        public int Id { get; set; }
        public double Gender { get; set; }
        public double AcademicMajor { get; set; }
        public double AcademicMinor { get; set; }
        public double AcademicInstitution { get; set; }
        public double SemesterNumber { get; set; }
        public double LastSemesterGrade { get; set; }
        public double AlertCount { get; set; }
        public double IsDroppedOut { get; set; }
        public int TraineeId { get; set; }
    }
}
