//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BelibaHoma.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorSession
    {
        public int Id { get; set; }
        public System.DateTime MeetingDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public double NumBondingHours { get; set; }
        public int TutorReportId { get; set; }
        public string MeetingPlace { get; set; }
    
        public virtual TutorReport TutorReport { get; set; }
    }
}
