//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BelibaHoma.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TutorReport()
        {
            this.Alert = new HashSet<Alert>();
            this.TutorSession = new HashSet<TutorSession>();
        }
    
        public int Id { get; set; }
        public int TutorTraineeId { get; set; }
        public double TutorHours { get; set; }
        public double TutorHoursBonding { get; set; }
        public string MeetingsDescription { get; set; }
        public bool IsProblem { get; set; }
        public System.DateTime CreationTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alert> Alert { get; set; }
        public virtual TutorTrainee TutorTrainee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TutorSession> TutorSession { get; set; }
    }
}
